version: '3.8'

services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/data
    restart: unless-stopped

volumes:
  h2_data:
